title: Stadium
email: 2002junha@postech.ac.kr
description: >- # this means to ignore newlines until "baseurl:"
  My website to record a variety of things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: wnsgkchoi

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate  # [추가됨] 페이지네이션 플러그인 활성화

future: true      # [추가됨] 미래 날짜(2025년 등) 포스트도 보이게 설정

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Pagination Settings
paginate: 10
paginate_path: "/page:num/"

# Exclude settings
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
